Add try/catch(NoClassDefFoundError) to debugging code in the socket protocol   so that it may be used without POST classes in the classpath (as is the case   in pastry-core.jar).